### ISSUE TITLE
Variables not appearing in constraints are not sampled

### ISSUE THREAD

**Issue by MathieuVavrille** [meelgroup/baital#1]
Hello,
I was using Baital when I discovered that some variables are not present in the returned sample file.
I think this is due to variables that exist, but are not present in any constraint (so any value is allowed). Such unconstrained variable can be created by FeatureIDE, for example with an optional feature directly linked to the root feature, and not appearing in cross-tree constraints.
More specifically, it seems that the variable is not returned only if it is the last variable of the problem.
I give you an example feature model (in UVL format, but the extension is .txt because github would not let me upload it).
[jnerd.txt](https://github.com/meelgroup/baital/files/9647859/jnerd.txt)
You should remark that the feature `Gradle` is not constrained. It is processed last by FeatureIDE, hence it is the 6th variable in the generated .dimacs file. When generating samples with baital, this variable is not present in the output samples.

I tested WAPS and I did not see the same issue. My guess would be that d4 or Dsharp are not used the same way in Baital and WAPS. In the generated .nnf file of Baital there is no occurence of the variable, but there is an occurence in the .nnf file generated by WAPS.

I hope that I was clear enough, I can give you more data (the generated dimacs, a comparison when exchanging the features `Maven` and `Gradle`, making `Gradle` the 5th variable, the sample files, etc) if necessary.

Best regards.

**Comment by edbaranov** [comment]
Hello,

Thank you for the feedback!
The difference with WAPS was caused by the usage of a different version of d4: the information of the total number of variables might be missed from the nnf file. 
The latest version should have the problem fixed.

Best regards,
